PURPLE_SUPER_DARK = "#29293d"
PURPLE_DARK = "#7575a3"
PURPLE = "#b3b3cc"
PURPLE_LIGHT = "#e0e0eb"
PURPLE_SUPER_LIGHT = "#f0f0f5"

WHITE_CHESS_PIECE = "white"
WHITE_CHESS_PIECE_BOERDER = PURPLE_SUPER_DARK
BLACK_CHESS_PIECE = PURPLE_DARK
BLACK_CHESS_PIECE_BOERDER = "white"

# Для терминала
BASE_COLOR_TERMINAL = "\x1B[0m"
GREEN_TERMINAL = "\x1B[32m"
RED_TERMINAL = "\x1B[31m"
YELLOW_TERMINAL = "\x1B[33m"
BLUE_TERMINAL = "\x1B[34m"
PURPLE_TERMINAL = "\x1B[35m"
