# Размеры окна
WINDOW_WIDTH  = 1000
WINDOW_HEIGHT = 740

CANVAS_WIDTH  = WINDOW_WIDTH - 300
CANVAS_HEIGHT = WINDOW_HEIGHT

# Для p2p
HOST_DEFAULT   = 'localhost'
PORT_FOR_WHITE = 6700
PORT_FOR_BLACK = 6800
