name: Chess App Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: python -m pip install --upgrade pip
          pip install flake8
      - name: Linting Chess App
        run: flake8 src
