name: Chess App Lint
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: python -m pip install --upgrade pip
          pip install pylint
      - name: Linting Chess App
        run: pylint src
